apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      containers:
        - name: demo-java-container
          image: kabeer17singh/kuberneteslearning:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: my-repo-secret